chore: version bump for studio and runtime 2.2.2
hyperon-io/hyperon_runtime_tutorial pull request #5
Opened 2022-11-28 09:11 UTC by idzSe

2022-11-29 17:49 UTC, Marcin-Decerto reviewed
Odapalałeś ten projekt po podbiciu? Nie trzeba było robić szacher macher z bazą?

2022-12-01 13:47 UTC, idzSe commented
Działa żadnych szacher z bazą robić nie trzeba, jest pięknie. Migracja starej bazy też poszła

2022-12-01 13:51 UTC, Emil-Wozniak requested changes

2022-12-01 13:51 UTC, Emil-Wozniak commented on src/test/java/pl/decerto/hyperon/guide/administration/AssignedElementsToRegionTest.java
> +import spock.lang.Ignore;
Ten ignore chyba jest już niepotrzebny

2022-12-02 10:10 UTC, idzSe commented on src/test/java/pl/decerto/hyperon/guide/administration/AssignedElementsToRegionTest.java
> +import spock.lang.Ignore;
Usunięte

2022-12-02 14:28 UTC, merged